version: '3'

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crudapp
    depends_on:
      - db
    ports:
    - "8080:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/db_news
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  db:
    image: postgres:15.1-alpine
    container_name: postgres
    networks:
      - app-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_news
    ports:
      - "5432:5432"
    volumes:
#      - ./pgdata:/var/lib/postgresql/data
#      - ./src/main/resources/db-init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data