version: '3'

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local

services:
  app:
    build:
      context: .
    container_name: crudapp
    depends_on:
      - db
  db:
    image: postgres:15.1-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jdbc:postgresql://localhost:5432/db_news
    volumes:
      - ./src/main/resources/db-init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data